export const themePalette = {
  accent: 'var(--tf-accent)',
  accentGhost: 'var(--tf-accent-ghost)',
  blue: 'var(--tf-primary)',
  blueStrong: 'var(--tf-primary-strong)',
  border: 'var(--tf-border)',
  borderStrong: 'var(--tf-border-strong)',
  dangerGhost: 'var(--tf-danger-ghost)',
  glass: 'var(--tf-surface)',
  glassSoft: 'var(--tf-surface-soft)',
  glassStrong: 'var(--tf-surface-strong)',
  green: 'var(--tf-success)',
  mutedSurface: 'var(--tf-surface-muted)',
  primaryGhost: 'var(--tf-primary-ghost)',
  red: 'var(--tf-danger)',
  shadow: 'var(--tf-shadow)',
  shadowStrong: 'var(--tf-shadow-strong)',
  successGhost: 'var(--tf-success-ghost)',
  textMain: 'var(--tf-text)',
  textMuted: 'var(--tf-text-tertiary)',
  textSecondary: 'var(--tf-text-secondary)',
};
